# Generated by Django 4.1.7 on 2023-12-11 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=20, unique=True)),
                ('store_name', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('item_list', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dashboardfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dashboardfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='filteredfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filteredfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnalyseFile',
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.DeleteModel(
            name='DashboardFile',
        ),
        migrations.DeleteModel(
            name='FilteredFile',
        ),
    ]
