# Generated by Django 4.1.7 on 2023-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receipt_remove_csvfile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
